USE [master]
GO

/****** Object:  Database [Documents]    Script Date: 25/10/2024 08:28:08 ******/
CREATE DATABASE [Documents]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Documents', FILENAME = N'C:\Users\ebar\Documents.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Documents_log', FILENAME = N'C:\Users\ebar\Documents_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Documents].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Documents] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Documents] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Documents] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Documents] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Documents] SET ARITHABORT OFF 
GO

ALTER DATABASE [Documents] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Documents] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Documents] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Documents] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Documents] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Documents] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Documents] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Documents] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Documents] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Documents] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Documents] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Documents] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Documents] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Documents] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Documents] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Documents] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Documents] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Documents] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Documents] SET  MULTI_USER 
GO

ALTER DATABASE [Documents] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Documents] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Documents] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Documents] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Documents] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Documents] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Documents] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Documents] SET  READ_WRITE 
GO


